### PR TITLE
Migrate from kotlin-argsparser to clikt

### PR DESCRIPTION
**Pull request by mbircu-ellation**
Jira: ETPAND-7709

### What has been done
1. Removed `jcenter()`
2. Migrated from https://github.com/xenomachina/kotlin-argparser to https://github.com/ajalt/clikt

- [x] Write unit tests

### How to test
Run the command below and make sure it doesn't fail
```Bash
kscript https://raw.githubusercontent.com/crunchyroll/android-library-release-script/ETPAND-7709-migrate-from-args-parser-to-clikt/src/main/kotlin/Release.kt --help
```

### CODE REVIEW

**Review by pr0t3us — APPROVED** [review]
👍  Checked with `dry-run` command on the dev-tools lib

**Comment by mbircu-ellation** [comment]
Will set it to draft, to add a Github Actions CI which will run the tests.

**Comment by mbircu-ellation** [comment]
It seems that running tests from Github Actions is not straightforward because some of the tests are simulating the test cases by running real bash commands.

**Review by pr0t3us — APPROVED** [review]

**Review by dmotpan — APPROVED** [review]

**Comment by mbircu-ellation** [comment]
Converted to draft because it seems that I'll need to add some more changes to make it CI-friendly.

**Comment by mbircu-ellation** [comment]
It seems that I was able to make it work without any changes 👍 
Switched back to review.

**Review by pr0t3us — APPROVED** [review]
👍 
```
#0  OK Upload artifact
#1  OK Create and push release tag
#2  OK Increment version in gradle.properties
#3  OK Update release date in changelog
#4  OK Add new version to changelog
#5  OK Create commit and pull request

```

**Pull request merged**
